### ISSUE TITLE
Toroidal vs Meanwell

### ISSUE THREAD

**Issue by cammas** [sparkybg/UniSolder-5.2#9]
Dear Unisolderers, can you please explain to me what makes a Meanwell [RPS-120-24](https://www.meanwell.com/webapp/product/search.aspx?prod=RPS-120) a worse power supply than a toroidal transformer? Thanks you!

**Comment by robpneu** [comment]
Below is sparkybg’s explanation ([source](https://dangerousprototypes.com/forum/index.php?topic=7218.msg61341#msg61341)); please note that “SMPS” means “Switching Mode Power Supply”, which is what most DC brick power supplies are (like those for laptops), and it looks like the supply you linked.

"In short using SMPS, you've got several times higher probabilities of something going wrong with the earth. Moreover, since JBC tips have a connection in them between the outer shell (which must be grounded) and one of the terminals, you should not ground the SMPS, but the tip itself. But most of the SMPS I've used, have a capacitor between one of the output terminals and ground/enclosure, so it needs a little thinking/experimentation where exactly to put the grounding and how to connect the wires between the power supply and controller, in order to avoid ground loops and some other things."

So if grounding is important to you (and for a bench iron, it probably should be), a toroidal transformer connected to AC mains and EARTH is recommended. To minimize clicking sounds, an epoxy impregnated transformer is best. To drive all of the possible handles, the ideal is a 24V, 6A transformer, which is 144 VA. 160VA is the most common power rating that I've seen that meets this criteria.

**Comment by cammas** [comment]
Ok so If I understand correctly a toroidal transformer is better than a crappy SMSPS? Can you a high quality SMPS? I need a power dense power supply that runs on 110 and 220VAC.

**Comment by robpneu** [comment]
From what I've seen on the forum, the only recommendation is don't do it. I don't think "high quality" makes a difference here.

**Comment by cammas** [comment]
Every few months with couple days notice. [relevant thread](https://www.eevblog.com/forum/projects/diy-jbc-nano/25/)

**Comment by robpneu** [comment]
I would suggest getting a 110/220 to 12/24 toroidal transformer, like [this one](https://octopart.com/vpt24-6670-triad+magnetics-10567051), and add a 110/220 switch on the back, like [this one](https://www.amazon.com/outstanding-Voltage-Selector-Terminals-Switches/dp/B07TWWBSBB).

You'd wire it so the output is always in series (giving you 24V), but the input would be switched between series (for 230 VAC) and parallel (for 115 VAC) using the switch above.

**Comment by labjr61** [comment]
I plan to build this project and I want the most reliable power supply. Nothing is more simple than a traditional transformer. If I wanted compact and lightweight for portability I would buy a Pinecil or TS100 iron.

BTW, this surplus house has a suitable transformer which was made in Canada by ILP which was a division of Plitron. So good quality. I have a couple of them already.  https://www.surplussales.com//item/_tp/t-2404a.html

**Comment by robpneu** [comment]
> I plan to build this project and I want the most reliable power supply. Nothing is more simple than a traditional transformer. If I wanted compact and lightweight for portability I would buy a Pinecil or TS100 iron.

Agreed. I really like my Pinecil; highly recommended for the portability!

> BTW, this surplus house has a suitable transformer which was made in Canada by ILP which was a division of Plitron. So good quality. I have a couple of them already. https://www.surplussales.com//item/_tp/t-2404a.html
That transformer looks good, though I don't think it would meet @cammas's voltage input needs since it looks like it only has a single input

**Comment by labjr61** [comment]
> That transformer looks good, though I don't think it would meet @cammas's voltage input needs since it looks like it only has a single input (at 120 V)

Oh I didn't see that single primary. I'd never have a transformer made with a single primary. I service electronic music equipment and Japanese companies like Roland and Yamaha always used single voltage transformers. That drives me crazy since they could've easily made it universal. I guess they did it for marketing reasons.

**Comment by sparkybg** [comment]
Just to mention - in the past, the firmware and hardware had some issues when working with low quality transofrers, but this was a long time ago. This is the reason of at least 2 of the older (pre 5.2) hardware revisions. From 5.2 on and with the later firmware, it can work with REALLY nasti transformers without any issues other than some clicking noise from the thansformer.

I recommend a high quality toridal, exactly because it is more compact, weights less, makes less audible noises, and has HUGELY less leakage inductance, which means HUGELY less inductive peaks and  HUGELY lower instability issues when 1/2. 1/4 and 1/8 power is used.

I don't know for original JBC controller with SMPS in it, and there's a reason for it - phisical connection between the outer shell of the tips and the heater, whish, as I mentioned, means that you must keep your entire SMPS not grounded and isolated from everything (including the case), and connect the earth ONLY to the tip's outer shell, which sometimes is hard to do.

Another thing to mention is that with SMPS you will have to get and overpowered unit or unit current limiter (not protection, but limiter). Some (maybe most) of them are reacting pretty fast on overcurrent, shutting the unit down. And some of the tips (C210 for еxample) have such low resistance that their peak current is much higher than averane current, which may trigger the SMPS protection.

So think a little more when deciding what power supply to choose - for reliable work you may end up with SMPS that is both larger and heavier than a simple 120-150VA toroidal, that handles peak currents of at least 3 times their rating without any problems.

**Comment by cammas** [comment]
To clarify, I wasn't asking if it's possible or not to use DC. Alot of people are buying and building theses kits, I was just wondering if power supplies could be referenced since they are required. Just like @labjr61 listed [toroidal](https://www.surplussales.com//item/_tp/t-2404a.html) If it was possible to list other power supplies people can buy to finish their unisolders. I hope my request is resonable for us to work on
